タイトル横のボタンを押すとゲームを中断できる機能を追加しました
teamdev-red/recursion-tetris-app pull request #26
Opened 2022-12-16 04:36 UTC by Atsu77

現在はページを開いた段階でゲームが自動で始まるので，ボタンを押すとゲームが始まるようにもしています．

2022-12-16 04:51 UTC, Atsu77 commented
![](https://github.trello.services/images/mini-trello-icon.png) [ゲームの一時中断機能を追加](https://trello.com/c/CauYybqj/42-%E3%82%B2%E3%83%BC%E3%83%A0%E3%81%AE%E4%B8%80%E6%99%82%E4%B8%AD%E6%96%AD%E6%A9%9F%E8%83%BD%E3%82%92%E8%BF%BD%E5%8A%A0)

2022-12-16 09:41 UTC, YukiYouda approved these changes

2022-12-16 09:42 UTC, YukiYouda commented
OKです！

2022-12-16 13:58 UTC, Youichi-Higa requested changes

2022-12-16 13:58 UTC, Youichi-Higa commented on src/models/gameState.ts
> +      console.log(gameButton);
`console.log(gameButton);`の削除お願いします！

2022-12-16 14:00 UTC, Youichi-Higa commented on src/models/gameState.ts
> +      console.log(gameButton);
自分もsubmitしてなくて、pending状態になってました。。

2022-12-17 00:41 UTC, Atsu77 commented on src/models/gameState.ts
> +      console.log(gameButton);
ご確認ありがとうございます．
すでに削除されているようです．

2022-12-17 01:30 UTC, Youichi-Higa approved these changes

2022-12-17 01:30 UTC, Youichi-Higa commented on src/models/gameState.ts
> +      console.log(gameButton);
確認しました！

2022-12-17 01:57 UTC, merged