スマホとタブレットのレスポンシブ対応
teamdev-red/recursion-tetris-app pull request #27
Opened 2022-12-16 10:15 UTC by Youichi-Higa

レスポンシブ対応させました！

スマホ
<img width="313" alt="スクリーンショット 2022-12-16 19 12 00" src="https://user-images.githubusercontent.com/83049578/208076034-b9f8c4c9-9036-47e4-beeb-b07442dc0b61.png">

タブレット
<img width="448" alt="スクリーンショット 2022-12-16 19 12 17" src="https://user-images.githubusercontent.com/83049578/208076098-704a0da0-f9f6-44ea-b6c4-1e023ca2d141.png">

2022-12-16 10:16 UTC, Youichi-Higa commented
![](https://github.trello.services/images/mini-trello-icon.png) [ゲームプレイ画面をレスポンシブに対応](https://trello.com/c/xo3twK1N/37-%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%97%E3%83%AC%E3%82%A4%E7%94%BB%E9%9D%A2%E3%82%92%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E3%81%AB%E5%AF%BE%E5%BF%9C)

2022-12-16 11:15 UTC, YukiYouda approved these changes

2022-12-16 11:15 UTC, YukiYouda commented
OKです！

2022-12-16 11:40 UTC, Atsu77 requested changes
レスポンシブの対応ありがとうございます！

特定の画面幅でこういう感じにになってしまうので，こちらの修正お願いします！
![image](https://i.imgur.com/FVDQz3w.png)

2022-12-16 13:54 UTC, Youichi-Higa commented
@Atsu77 
特定の幅での表示崩れを修正しました！

2022-12-17 01:31 UTC, Atsu77 approved these changes

2022-12-17 01:36 UTC, merged